ignorePatterns:
  - .next/
  - out/
  - public/sw.js
  - public/workbox-*.js
env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - local-rules
rules: {}
overrides:
  - files:
      - 'pages/**/*.js'
      - 'pages/**/*.jsx'
    rules:
      local-rules/require-page-default-export: error
